### ISSUE TITLE
self signed certificate in certificate chain

### ISSUE THREAD

**Issue by Pratima81** [IBM/watson-banking-chatbot#98] opened 2019-02-22 05:29 UTC
I downloaded this project and tried to run it. But i am constantly getting this error as shown below.
Any help can be appreciated.

![image](https://user-images.githubusercontent.com/37571151/53221598-77489b80-36ad-11e9-8807-70bc307d9c69.png)

**Comment by markstur** [comment] 2019-04-10 19:54
I can't reproduce this error. It could be a config problem. Check your .env and make sure the URLs are correct. If you are really getting this error from IBM Cloud, what is your ASSISTANT_URL and what region is your Assistant service in?

Note, the local app is not secure just using http://0.0.0.0:3000 (https w/ cert is out of scope) but it looks like that isn't the problem here.  listWorkspaces() should not fail if configured correctly.

**Closed** 2019-04-22 19:36 UTC
